<template>

<div class="loadingio-spinner-wedges-u6kpdfapqw">
    <div class="ldio-4gx0uvcob8l">
        <div>
            <div>
                <div>
                
                </div>
            </div>
            <div>
                <div>
                
                </div>
            </div>
            <div>
                <div>
                
                </div>
            </div>
            <div>
                <div>
                
                </div>
            </div>
        </div>
    </div>
</div>


</template>


<script>
export default {
    setup(){
    return {  }
    }
};
</script>


<style lang="scss" scoped>
@keyframes ldio-4gx0uvcob8l {
  0% { transform: rotate(0deg) }
  100% { transform: rotate(360deg) }
}
.ldio-4gx0uvcob8l > div > div {
  transform-origin: 121.50000000000001px 121.50000000000001px;
  animation: ldio-4gx0uvcob8l 2.127659574468085s linear infinite;
  opacity: 0.88
}
.ldio-4gx0uvcob8l > div > div > div {
  position: absolute;
  left: 31.590000000000003px;
  top: 31.590000000000003px;
  width: 89.91000000000001px;
  height: 89.91000000000001px;
  border-radius: 89.91000000000001px 0 0 0;
  transform-origin: 121.50000000000001px 121.50000000000001px
}.ldio-4gx0uvcob8l > div div:nth-child(1) {
  animation-duration: 0.5319148936170213s
}
.ldio-4gx0uvcob8l > div div:nth-child(1) > div {
  background: #56c7fb;
  transform: rotate(0deg);
}.ldio-4gx0uvcob8l > div div:nth-child(2) {
  animation-duration: 0.7092198581560283s
}
.ldio-4gx0uvcob8l > div div:nth-child(2) > div {
  background: #79e7ab;
  transform: rotate(0deg);
}.ldio-4gx0uvcob8l > div div:nth-child(3) {
  animation-duration: 1.0638297872340425s
}
.ldio-4gx0uvcob8l > div div:nth-child(3) > div {
  background: #ccf3fd;
  transform: rotate(0deg);
}.ldio-4gx0uvcob8l > div div:nth-child(4) {
  animation-duration: 2.127659574468085s
}
.ldio-4gx0uvcob8l > div div:nth-child(4) > div {
  background: #2a2d3a;
  transform: rotate(0deg);
}
.loadingio-spinner-wedges-u6kpdfapqw {
  width: 243px;
  height: 243px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0);
}
.ldio-4gx0uvcob8l {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-4gx0uvcob8l div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>